activemq:
  image: motech/activemq:5.5.1
  ports:
    - 61616:61616
    - 8161:8161
couchdb:
  image: motech/couchdb:1.5.0
  ports:
    - 5984:5984
    - 5985:5985
db:
  image: motech/mysql
  ports:
    - 3306:3306
#  volumes:
#    - /mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: quartz
    MYSQL_PASSWORD: quartz2123
    MYSQL_DATABASE: motechquartz
tomcat:
  image: motech/tomcat:7.0.53
  ports:
    - "8080:8080"
    - "8000:8000"
  links:
    - couchdb
    - db
    - activemq
  environment:
    JAVA_OPTS: -Xms1024m -Xmx2048m -XX:MaxPermSize=1024m
    DB_TYPE: mysql
    DB_USER: root
    DB_PASSWORD: password
  volumes:
    - /home/HOST_USERNAME/docker-motech-config:/root/.motech/config
    - /home/HOST_USERNAME/docker-motech-bundles:/root/.motech/bundles
